### ISSUE TITLE
java.lang.outofmemoryerror for sound folder directory.

### ISSUE THREAD

**Issue by Demonslayerx8** [kotcrab/fate-explorer#1]
I seem to be getting an issue when it comes to getting all the files, mostly when it comes to extracting the AWB files from the sound folder.
https://cdn.discordapp.com/attachments/364598497577664513/472949685125120010/unknown.png

Any idea what's causing it? This is with the pk extract tool for fate extella link.

**Comment by kotcrab** [comment]
You just need to throw more RAM at it.

Edit `bin/pktools.bat` and change `set DEFAULT_JVM_OPTS=` to
```
set DEFAULT_JVM_OPTS=-Xms2048m -Xmx2048m
```

You can also check if you have 64 bit JRE/JDK installed. Do `java -version` from cmd, should say somewhere there that it is 64 bit.

**Comment by kotcrab** [comment]
Going to close this but fell free to comment if you still have this issue after applying changes from above comment.
